navbar functionality added styling
kshep425/30-Minute-Workouts pull request #25
Opened 2019-12-04 02:37 UTC by MHavrilak

2019-12-04 03:55 UTC, kshep425 commented on assets/css/style.css
> +    margin: 10px
add semi colon

2019-12-04 03:59 UTC, kshep425 requested changes
Can you make the updates?  Then I'll approve it.

2019-12-04 03:59 UTC, kshep425 commented on index.html
>                              <span aria-hidden="true"></span>
Should anything be in these spans?

2019-12-04 03:59 UTC, kshep425 commented on index.html
> +                    <div id="navbarBasic" class="navbar-menu is active">
Can you change id's to be underlined?

2019-12-04 03:59 UTC, kshep425 commented on index.html
> +        <button class="button is-primary is-outlined is-rounded" type="input" id="start">Start Workout!</button>
Very nice change!

2019-12-04 04:29 UTC, MHavrilak commented on assets/css/style.css
> +    margin: 10px
fixed

2019-12-04 23:23 UTC, kshep425 reviewed
I don't see the changes.  You may need to push and do another pull request.

2019-12-05 01:10 UTC, kshep425 approved these changes

2019-12-05 01:10 UTC, merged